terminate called after throwing an instance of 'std::runtime_error'
  what():  AssignmentOperator::code_gen is not implemented.
